### ISSUE TITLE
Custom heading elements not converted when the editor loads

### ISSUE THREAD

**Issue by Mattho25** [ckeditor/ckeditor5-heading#110]
Hi,

I thought I made a mistake while trying to add custom headings (https://github.com/ckeditor/ckeditor5/issues/1148), but it seems to be a real issue of the Headings plugin as the problem also appear in the Heading documentation  sample (https://docs.ckeditor.com/ckeditor5/latest/features/headings.html).

For instance, if we have two headings : `<h2>` and `<h2 class="fancy">`, then despite the priority of the second one set to "high" (`priority: 'high'`), the editor will miss the conversion of the custom heading and will lead to the generic heading transformation.

As you can see in the documentation, while `Heading 2 (fancy)` is correctly defined and is useable, the editor has converted `<h2 class="fancy">` to a simple `<h2>` : 

The editor show two times the same `<h2>` :
![image](https://user-images.githubusercontent.com/12222956/42593738-9379e988-854d-11e8-8355-a6b969730975.png)

Despite the actual text set to `<h2 class="fancy">`
![image](https://user-images.githubusercontent.com/12222956/42593991-2bffef86-854e-11e8-9044-d7cdd2b4ec26.png)

I am also wondering how will this plugin handle one generic tag and two custom headings based on it, e.g. `<h2>`, `<h2 class="fancy">` & `<h2 class="decorative">`. The "priority" seems weird to use in this case as we will want both custom heading to appear when specified.

Could it be possible to fix this issue shortly? Thank you!

**Comment by jodator** [comment]
@Mattho25 Thanks for reporting. Looks like we forgot to update documentation after [changing](https://github.com/ckeditor/ckeditor5-engine/pull/1413#issuecomment-386636499) `priority` to `converterPriority` :(

This will work:
```js
heading: {
	options: [
		{ model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
		{ model: 'heading1', view: 'h1', title: 'Heading 1', class: 'ck-heading_heading1' },
		{ model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' },
		{
			model: 'headingFancy',
			view: {
				name: 'h2',
				classes: 'fancy'
			},
			title: 'Heading 2 (fancy)',
			class: 'ck-heading_heading2_fancy',
			converterPriority: 'high'
		}
	]
}
```

**Comment by jodator** [comment]
@Mattho25 Great to hear that :)

We have a link there to [`ElementDefinition`](https://docs.ckeditor.com/ckeditor5/latest/api/module_engine_view_elementdefinition-ElementDefinition.html#) for the `.view` so it kinda is somewhere noted. That being said it might not be discoverable enough as in your case.

I wonder if we shouldn't provide such choice do end-developers and only provide one way of `classes`? (cc @Reinmar, @pjasiun):
```js
view: {
	name: 'h2',
	classes: [ 'fancy' ]
}
// vs:
view: {
	name: 'h2',
	classes: 'fancy'
}
```
The above comment from @Mattho25 might be a valid case to think about that.

**Comment by Mattho25** [comment]
In my opinion, only allowing an array of class names would avoid any confusion. :)

**Comment by Reinmar** [comment]
If we only supported classes but wouldn't throw, then passing a string might coincidentally work...

Imagine this:

```js
addClasses( classes ) {
     // Let's say we need to clone the param e.g. to filter out something
     // we must not change the param by reference.
     const classesToAdd = Array.from( classes );
 
     // ...something...

     classes.forEach( class => this.domElement.classList.add( class ) );
}

addClasses( 'justastring' ); // Silent error...
```

Yey!

```
<element classes="j u s t a r i n g">
```

So, in any way, we'd need to throw on that. 

BTW, alternatively, we could handle `classes` and `class` in the same way. This will be cheap.
