### ISSUE TITLE
Provide h4, h5, h6 as defaultIcons for button view and add translations for items

### ISSUE THREAD

**Issue by MCMicS** [ckeditor/ckeditor5-heading#121]
With #112 the icons for h4 - h6 was provided but in defaultIcons it is still missing.

_headingbuttonsui.js_
```
const defaultIcons = {
	heading1: iconHeading1,
	heading2: iconHeading2,
	heading3: iconHeading3
};
```

Also the translations are only set for Heading 1 to Heading 3

**Comment by oleq** [comment]
Why the PR was closed?

**Comment by MCMicS** [comment]
@oleq I have used wrong author. Have create a new PR.

**Comment by MCMicS** [comment]
When will the new messages synchronized with transifex?
Because I can't see them as untranslated there.

**Comment by Reinmar** [comment]
Sorry! And thanks for reminding us about this. Syncing them right now.

**Comment by Reinmar** [comment]
Done:

![image](https://user-images.githubusercontent.com/156149/51520637-82957680-1e24-11e9-8a7e-9f411fcbc4b6.png)

We download them back usually before a release.
