### ISSUE TITLE
Mark the current heading in the dropdown list

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-heading#26]
Currently, the current option is only visible in the dropdown button. It should also be marked inside the panel.

**Comment by oleq** [comment]
What would you say about it?

![dropdown-active-item](https://cloud.githubusercontent.com/assets/1099479/23761575/8d6de016-04f3-11e7-811b-5b33500643cc.gif)

**Comment by Reinmar** [comment]
I always have problems with active/inactive states. If you have just two options to choose from and one of them is active in a lot of apps you have no idea which of these options is the active one and which is inactive.

One notable example here – Sublime Text:

![image](https://cloud.githubusercontent.com/assets/156149/23761955/ea321136-04f4-11e7-90ae-307e8779bd23.png)

I'm working with this app every day and I still don't know which option is selected.

What's worse – this extends even if there are more options than 2. Since the style itself is pretty indistinguishable there's no "tick" when I notice it. It usually takes me a couple of arrow down/up key presses to figure out where the damn selection is in Sublime's panel.

In the example you showed the focus is clearly marked using an intuitive glow, so that's, I think, ok.

However, the active/inactive styling would fail the same test which Sublime fails. This isn't too important now because most of the time you'll have more than 2 options in that panel, but if you have a better idea for that style, I'd be happy to see it :D.

PS. There's also https://github.com/ckeditor/ckeditor5-heading/issues/55 to fix (I mention it because it's visible on the screencast).

**Comment by oleq** [comment]
We could invert active selection. This is what OSs usually do:
![dropdown-invert](https://cloud.githubusercontent.com/assets/1099479/23787243/698c9b14-0571-11e7-8635-e1f3974777de.gif)

**Comment by Reinmar** [comment]
Slack uses similar styling (color for active, slight shade change for hover) in its channel list and I think I like it. But macOS uses a bit different styling for its top menu AFAICS – hover is color and active has a check mark :D. But a similar to Slack's styling is used e.g. in Messages (on the left) and it's fine.

OTOH, personally, I'll have to get used to this blue background. ATM, it stands out pretty strongly. I guess that I'd just need time.

**Comment by oleq** [comment]
Some experiments with ticks

![image](https://cloud.githubusercontent.com/assets/1099479/23790865/2d224150-0581-11e7-9fa7-926534bd2834.png)

**Comment by oleq** [comment]
And hued color without text inversion
![image](https://cloud.githubusercontent.com/assets/1099479/23790896/492b360e-0581-11e7-8e41-87dd1ef76ace.png)

**Comment by oleq** [comment]
Combined:
![combined](https://cloud.githubusercontent.com/assets/1099479/23791122/22f106a2-0582-11e7-99a6-c6ccec324137.gif)

**Comment by Reinmar** [comment]
All fine for me. Maybe just small doubt about the tick – that it moves the text to the right. In native macOS menus it has a reserved space on the left, so adding the check mark doesn't move the item.

**Comment by oleq** [comment]
A good point.

![image](https://cloud.githubusercontent.com/assets/1099479/23791912/282dbb4e-0585-11e7-9fa1-34c17e9c2229.png)

**Comment by Reinmar** [comment]
![screen shot 2017-03-10 at 11 34 36](https://cloud.githubusercontent.com/assets/156149/23792054/b499b786-0585-11e7-9581-3aa39ef937ef.png)

I noticed on the early screenshots that the items are not aligned well. Is this some styling issue?

**Comment by oleq** [comment]
> Needs some tuning though.

I updated my response.

**Comment by Reinmar** [comment]
So, I like: 

![image](https://cloud.githubusercontent.com/assets/156149/23792116/fb548d22-0585-11e7-9304-9e0e97c8d9b1.png)

And:

![image](https://cloud.githubusercontent.com/assets/156149/23792129/062a7c34-0586-11e7-828c-fe8605954d76.png)

And (if the items were aligned):

![image](https://cloud.githubusercontent.com/assets/156149/23792148/10dbe618-0586-11e7-991f-c79f7476ec93.png)

In the first solution, I'm not sure about the bright, panty color (maybe if it was the same as the focused border of the editable?). E.g. the stronger one in the second solution looks better to me, though, it may stand out too much. In the 3rd option there's no problem with color, cause it's grey so it may be the easiest option :D.

**Comment by oleq** [comment]
> In the first solution, I'm not sure about the bright, panty color (maybe if it was the same as the focused border of the editable?). E.g. the stronger one in the second solution looks better to me, though, it may stand out too much.

This one is pretty rough IMO, but it also makes sense. 

![image](https://cloud.githubusercontent.com/assets/1099479/23792409/10e080b4-0587-11e7-8f8f-789a795b11fe.png)

I'll make up my mind and create a PR ;-)
