### ISSUE TITLE
Element's names or attributes?

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-heading#27]
We should discuss whether we are fine with current implementation that uses several model elements: `heading1`, `heading2`, etc. or maybe we could change it to one element `heading` with `level` attribute.

What do we gain?
1. It is more semantically correct and looks better.
2. Less converters (no need to specify converter for each heading even if adding them is nearly automatic).
3. Less schema stuff.
4. Easier integration with other features (i.e. no need to check whether block name is one of many elements).

**Comment by fredck** [comment]
I'm for `heading + attribute`.

**Comment by Reinmar** [comment]
If we go with attributes, then schema will need to be able to validate attribute values. I'm fine with that of course. We'll have to rethink the schema anyway.

**Comment by scofalik** [comment]
Why is that? I meant `heading` element plus `level` attribute. Then schema will only have to check `heading` name. Will there be any case that heading of given level is forbidden or allowed where heading of other level is not ?

**Comment by Reinmar** [comment]
> Will there be any case that heading of given level is forbidden or allowed where heading of other level is not ?

Yes, it may happen. If the heading feature is configured to accept only h2-h3, then it should reject the rest. Most of the job will be done on conversion (so without touching the schema), but theoretically, someone may want to allow bold only in h3, because it's invisible in h2 (real case in fact). Or that the main heading (h2) should only accept plain text but not the rest (cc @pjasiun ;>). We can also imagine other cases where a structure could depend on values of such attributes.

Of course, we don't have to support this from the day one, but it will be pity to not consider it when redesigning the schema.

**Comment by pjasiun** [comment]
I agree with @Reinmar. But at the same time, I agree that schema needs to be rethinked because it is far too limited right now. So I don't think it is a headers representation problem. It is a scheme problem and the header representation is not the only case.

**Comment by scofalik** [comment]
So what's a conclusion here? Do we want to change to `heading` model element + `level` attribute? AFAICS @pjasiun, @fredck and me are for it, @Reinmar is against it?

Keep in mind that `Schema` will be probably totally rewritten, so let's not decide basing on it.

**Comment by Reinmar** [comment]
I'm fine with attributes.

**Comment by oleq** [comment]
I've noticed that with each PR we're getting deeper and deeper with the `headingN` rather than `heading+attribute` concept. Is the issue still valid? It seems long forgotten.

**Comment by Reinmar** [comment]
I don't think that we'll ever switch to the `heading+attribute` pair. We're too far in the Schema to support this reliably and it might only complicate things. Ensuring that two values (the name of an element and value of the attribute) meet certain criteria is always harder than checking just one name.
