### ISSUE TITLE
Heading dropdown's label isn't refreshed

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-heading#45]
![heading-bug](https://cloud.githubusercontent.com/assets/156149/20101190/2b301518-a5c1-11e6-9899-6b1d9d55f9a9.gif)

**Comment by Reinmar** [comment]
There are multiple cases in which the label isn't updated:

* https://github.com/ckeditor/ckeditor5-heading/issues/47
* https://github.com/ckeditor/ckeditor5-heading/issues/46

**Comment by oleq** [comment]
The bug is on the command side. Checked 
```js
dropdownModel.bind( 'label' ).to( command, 'value', format => format.label );
``` 

binding that sets the label and the `change:value` is not fired .

**Comment by szymonkups** [comment]
This is directly linked with: https://github.com/ckeditor/ckeditor5-engine/issues/697
