### ISSUE TITLE
FormatsCommand should use schema.

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-heading#5]
Current `FormatsCommand` implementation is not using schema at all. It assumes that blocks are placed directly inside root element and converts only them.

**Comment by oleq** [comment]
@szymonkups Has https://github.com/ckeditor/ckeditor5-heading/issues/73 fixed the issue? I suppose there has been lots of refactoring since you created this issue so maybe it's completely out–of–date?

**Comment by szymonkups** [comment]
Yep, it's out-of-date. We are checking schema now in `HeadingCommand`, If there will be any problems with that more specific issues should be reported. I am closing the issue.
