### ISSUE TITLE
No "tick" for selected option

### ISSUE THREAD

**Issue by fredck** [ckeditor/ckeditor5-heading#65]
I know that in #26 it has been decided to move ahead with "tick" + "blue background" for the selected option in the list.

I would propose removing the tick:

 * It's a duplication of the "blue background", being superfluous, therefore.
 * It creates an ugly padding on the left of the list.
 * The fewer UI elements, the better.
 * It's ugly :P

**Comment by Reinmar** [comment]
After seeing this live I agree with @fredck. Also, I liked the dropdown that you showed me @oleq yesterday – it used only a blue bg color.

**Comment by Reinmar** [comment]
Related issue: https://github.com/ckeditor/ckeditor5-heading/issues/63
