### ISSUE TITLE
[Chrome] Multiple heading change moves caret upwards 

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-heading#77]
## Steps to reproduce
1. Open classic editor sample.
2. Put a caret at first paragraph (below first header).
3. Transform it multiple times by clicking "Heading 1" (like on the gif below).

## Current result
Caret moves upwards and transforms header above instead of paragraph.

## GIF 
![bug](https://cloud.githubusercontent.com/assets/20988892/26778647/6ac5089e-49e2-11e7-9a3b-362c16bb88db.gif)

## Other information
OS: Windows 10
Browser: Chrome
Release: 0.10.0

**Comment by oleq** [comment]
Please make sure this is not https://github.com/ckeditor/ckeditor5-ui/issues/228, which has already been fixed.

**Comment by Mgsy** [comment]
Actually, I think this is the same issue. Thanks for an information, I'm closing this one.

**Comment by oleq** [comment]
Thanks! I suppose it could save you some time if you tested masters. Our iterations are pretty long and many things broken in http://ckeditor5.github.io are already fixed.

**Comment by Mgsy** [comment]
I'm testing on my local build, but I noticed it wasn't updated. Now everything is fine and indeed this bug doesn't exist anymore. Sorry for that ;)
