### ISSUE TITLE
Transforming an image into a paragraph shouldn't be possible

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5-heading#80]
## Steps to reproduce
1. Open a sample with an image.
2. Start a selection from the beginning of the document and drag it down until the image is selected.
3. Select the dropdown list.
4. Click on the "Paragraph".

## Current result
The image inside the `<figure>` element has transformed into a paragraph.

## Notes
- Bug isn't reproducable on Edge.
- Applying headers to the image doesn't make any changes inside the `<figure>` element.
- I belive this issue is related with: 
 https://github.com/ckeditor/ckeditor5-list/issues/62 
 https://github.com/ckeditor/ckeditor5-block-quote/issues/10

## GIF
![bug](https://user-images.githubusercontent.com/20988892/26927175-149bf57e-4c51-11e7-89dd-b4d0bf76465e.gif)

## Other information
OS: Windows 10, MacOS X
Browser: Chrome, Firefox, Safari

**Comment by oleq** [comment]
A [PR](https://github.com/ckeditor/ckeditor5-heading/pull/76) fixing similar issues have been merged recently. Can you confirm the issue occurs in the latest master branch of ckeditor5-headings?

**Comment by Mgsy** [comment]
>Can you confirm the issue occurs in the latest master branch of ckeditor5-headings?
Yes, it's reproducable. A thing is, when I try to apply a header, editor behaves like expected. Issue occurs only when I apply a paragraph.

In this case I wonder if I placed this issue in a correct place, probably it should fit to the paragraph repo. Shall I move it there?

**Comment by oleq** [comment]
Thanks, @Mgsy. There's no such need. I've just moved it to https://github.com/ckeditor/ckeditor5-paragraph/issues/24.
