### ISSUE TITLE
[Docs] Block elements got merged after changing multiple blocks to a heading

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-heading#86]
### Steps to reproduce

1. Go to a sample, for example https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/headings.html.
2. Select all the content in the sample.
3. Change to `Heading 1`.

### Expected result

There are three headings of level one.

### Current result

Paragraph got merged with the second block.

![image](https://user-images.githubusercontent.com/1502228/31071375-1d3de80e-a764-11e7-9a9b-bc4b7a8dccda.png)

**Comment by scofalik** [comment]
For some reason this happens only when you use `Heading 1`, not other options.

**Comment by Reinmar** [comment]
Confirmed. But weeird.

![image](https://user-images.githubusercontent.com/156149/31071452-4ccb2ff0-a764-11e7-8b08-e807fda65d68.png)

**Comment by Reinmar** [comment]
It may be a problem with h1 styling in the docs page.

**Comment by Reinmar** [comment]
Yep. That's due to display: inline-block. And there are more problematic styles there. I'll handle that.
