### ISSUE TITLE
Outlines on dropdown options

### ISSUE THREAD

**Issue by vladikoff** [ckeditor/ckeditor5-heading#91]
Is this expected to have the blue outlines on the selected options? See gif below. 

Not sure if by design and needs to be CSS fixed.

<img src="https://user-images.githubusercontent.com/31244235/33180303-e8de67c0-d074-11e7-99f5-105d776ada00.gif">

Ref: https://github.com/mozilla/notes/issues/438

**Comment by oleq** [comment]
Yes, these are just focus styles. In a focused editor press (<kbd>Fn</kbd>)<kbd>Alt</kbd>+<kbd>F10</kbd> and using arrows keys navigate inside a dropdown (also the toolbar) to see how it works. 

Do you think our approach is wrong? Maybe these styles should never show up when using a mouse? TBH, this does not look like anything serious.

**Comment by vladikoff** [comment]
We fixed it by changing css on our end, reopen if anyone needs it  👍
