### ISSUE TITLE
Can a post-fixer handle "make paragraph on enter at the end of a heading"?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-heading#93]
I found this in the code:

```js
			// @TODO This should be handled by a post-fixer.
			this.listenTo( enterCommand, 'afterExecute', ( evt, data ) => {
				const positionParent = editor.model.document.selection.getFirstPosition().parent;
				const isHeading = options.some( option => positionParent.is( option.model ) );

				if ( isHeading && !positionParent.is( defaultModelElement ) && positionParent.childCount === 0 ) {
					data.writer.rename( positionParent, defaultModelElement );
				}
			} );
```

This note was added by @oskarwrobel recently. How can this be handled by a post-fixer without breaking valid cases where a heading is being inserted after another heading?

**Comment by oskarwrobel** [comment]
I realized it cannot be a post-fixer and I was sure I removed this comment :)

**Comment by scofalik** [comment]
Do I understand correctly that it changes empty headings (or `option.model`) into paragraphs (or `defaultModelElement`) after the command is used?

How can we differentiate between "correct" empty heading and "incorrect" empty heading? If we can, then we can do it in post-fixer. But I am not sure it will be easy.

**Comment by Reinmar** [comment]
I'll remove this comment. Thanks.
